
# Site settings
url: 'https:cultureerevolte.nl'
baseurl: ''
title: null
#title: 'Culturée Revolté'
description: 'Cultuur om van te Kotsen'
theme: jekyll-theme-hacker
github:
  is_project_page: false
